<a href="https://colab.research.google.com/github/sonhh-3626/data-science-economics/blob/main/transformation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Bài thực hành: Sắp xếp và Biến đổi dữ liệu (Sorting & Data Transformation) trong Pandas**

In [15]:
import pandas as pd
import numpy as np

# Khởi tạo tập dữ liệu đơn hàng
data_donhang = {
    'MaDH': ['DH01', 'DH02', 'DH03', 'DH04', 'DH05', 'DH06', 'DH07'],
    'KhachHang': ['An', 'Bình', 'Cường', 'Đông', 'An', 'Hà', 'Nam'],
    'SanPham': ['Laptop', 'Chuột', 'Laptop', 'Bàn phím', 'Màn hình', 'Laptop', 'Chuột'],
    'SoLuong': [1, 2, 1, 3, 2, 1, 4],
    'DonGia': [1500, 25, 1500, 45, 300, 1600, 20],
    'KhuVuc': ['Hà Nội', 'Đà Nẵng', 'Hồ Chí Minh', 'Hà Nội', 'Đà Nẵng', 'Hà Nội', 'Hồ Chí Minh']
}

df = pd.DataFrame(data_donhang)
display(df)

   MaDH KhachHang   SanPham  SoLuong  DonGia       KhuVuc
0  DH01        An    Laptop        1    1500       Hà Nội
1  DH02      Bình     Chuột        2      25      Đà Nẵng
2  DH03     Cường    Laptop        1    1500  Hồ Chí Minh
3  DH04      Đông  Bàn phím        3      45       Hà Nội
4  DH05        An  Màn hình        2     300      Đà Nẵng
5  DH06        Hà    Laptop        1    1600       Hà Nội
6  DH07       Nam     Chuột        4      20  Hồ Chí Minh

## **I. Sắp xếp dữ liệu (Sorting)**

In [16]:
# 1. Sắp xếp giảm dần theo DonGia
df_sort_dongia = df.sort_values(by='DonGia', ascending=False)
print("Sắp xếp theo DonGia giảm dần:")
display(df_sort_dongia)

# 2. Sắp xếp theo KhuVuc (tăng dần) và SoLuong (giảm dần)
df_sort_multi = df.sort_values(by=['KhuVuc', 'SoLuong'], ascending=[True, False])
print("\nSắp xếp theo KhuVuc (tăng dần) và SoLuong (giảm dần):")
display(df_sort_multi)

# 3. Tạo lại chỉ mục mới sau khi sắp xếp
df_sorted = df_sort_multi.reset_index(drop=True)
print("\nBảng dữ liệu sau khi reset index:")
display(df_sorted)

Sắp xếp theo DonGia giảm dần:

   MaDH KhachHang   SanPham  SoLuong  DonGia       KhuVuc
5  DH06        Hà    Laptop        1    1600       Hà Nội
2  DH03     Cường    Laptop        1    1500  Hồ Chí Minh
0  DH01        An    Laptop        1    1500       Hà Nội
4  DH05        An  Màn hình        2     300      Đà Nẵng
3  DH04      Đông  Bàn phím        3      45       Hà Nội
1  DH02      Bình     Chuột        2      25      Đà Nẵng
6  DH07       Nam     Chuột        4      20  Hồ Chí Minh

Sắp xếp theo KhuVuc (tăng dần) và SoLuong (giảm dần):

   MaDH KhachHang   SanPham  SoLuong  DonGia       KhuVuc
3  DH04      Đông  Bàn phím        3      45       Hà Nội
0  DH01        An    Laptop        1    1500       Hà Nội
5  DH06        Hà    Laptop        1    1600       Hà Nội
6  DH07       Nam     Chuột        4      20  Hồ Chí Minh
2  DH03     Cường    Laptop        1    1500  Hồ Chí Minh
1  DH02      Bình     Chuột        2      25      Đà Nẵng
4  DH05        An  Màn hình        2     300      Đà Nẵng

Bảng dữ liệu sau khi reset index:

   MaDH KhachHang   SanPham  SoLuong  DonGia       KhuVuc
0  DH04      Đông  Bàn phím        3      45       Hà Nội
1  DH01        An    Laptop        1    1500       Hà Nội
2  DH06        Hà    Laptop        1    1600       Hà Nội
3  DH07       Nam     Chuột        4      20  Hồ Chí Minh
4  DH03     Cường    Laptop        1    1500  Hồ Chí Minh
5  DH02      Bình     Chuột        2      25      Đà Nẵng
6  DH05        An  Màn hình        2     300      Đà Nẵng

## **II. Biến đổi dữ liệu (Data Transformation)**

In [17]:
# 1. Tạo cột ThanhTien
df_sorted['ThanhTien'] = df_sorted['SoLuong'] * df_sorted['DonGia']

# 2. Phân loại cột MucGia dựa vào DonGia
def phan_loai_gia(dongia):
    if dongia >= 1000:
        return 'Cao'
    elif 300 <= dongia < 1000:
        return 'Trung bình'
    else:
        return 'Thấp'

df_sorted['MucGia'] = df_sorted['DonGia'].apply(phan_loai_gia)

# 3. Chuẩn hóa tên khách hàng thành chữ in hoa
df_sorted['KhachHang'] = df_sorted['KhachHang'].str.upper()

display(df_sorted)

,MaDH,KhachHang,SanPham,SoLuong,DonGia,KhuVuc,ThanhTien,MucGia
0,DH04,ĐÔNG,Bàn phím,3,45,Hà Nội,135,Thấp
1,DH01,AN,Laptop,1,1500,Hà Nội,1500,Cao
2,DH06,HÀ,Laptop,1,1600,Hà Nội,1600,Cao
3,DH07,NAM,Chuột,4,20,Hồ Chí Minh,80,Thấp
4,DH03,CƯỜNG,Laptop,1,1500,Hồ Chí Minh,1500,Cao
5,DH02,BÌNH,Chuột,2,25,Đà Nẵng,50,Thấp
6,DH05,AN,Màn hình,2,300,Đà Nẵng,600,Trung bình

## **III. Tổng hợp và phân tích dữ liệu (Groupby)**

In [18]:
# 1. Tổng doanh thu (ThanhTien) theo từng KhuVuc
doanh_thu_khuvuc = df_sorted.groupby('KhuVuc')['ThanhTien'].sum().reset_index()
print("Tổng doanh thu theo từng Khu Vực:")
display(doanh_thu_khuvuc)

# 2. Số lượng đơn hàng của từng SanPham
don_hang_sanpham = df_sorted.groupby('SanPham').size().reset_index(name='SoLuongDonHang')
print("\nSố lượng đơn hàng của từng Sản Phẩm:")
display(don_hang_sanpham)

# 3. Giá trị đơn hàng trung bình theo từng Khách hàng
gia_tri_tb_khach = df_sorted.groupby('KhachHang')['ThanhTien'].mean().reset_index(name='GiaTriTrungBinh')
print("\nGiá trị đơn hàng trung bình của mỗi Khách Hàng:")
display(gia_tri_tb_khach)

Tổng doanh thu theo từng Khu Vực:

        KhuVuc  ThanhTien
0       Hà Nội       3235
1  Hồ Chí Minh       1580
2      Đà Nẵng        650

Số lượng đơn hàng của từng Sản Phẩm:

    SanPham  SoLuongDonHang
0  Bàn phím               1
1     Chuột               2
2    Laptop               3
3  Màn hình               1

Giá trị đơn hàng trung bình của mỗi Khách Hàng:

  KhachHang  GiaTriTrungBinh
0        AN           1050.0
1      BÌNH             50.0
2     CƯỜNG           1500.0
3        HÀ           1600.0
4       NAM             80.0
5      ĐÔNG            135.0

Doanh thu theo khu vực:
- Hà Nội dẫn đầu với tổng doanh thu 3,235.
- Hồ Chí Minh đứng thứ hai với 1,580.
- Đà Nẵng đứng cuối với 650.

Số lượng đơn hàng theo sản phẩm: Laptop là sản phẩm phổ biến nhất với 3 đơn hàng, tiếp theo là Chuột (2 đơn), Màn hình và Bàn phím (mỗi loại 1 đơn).

Giá trị trung bình mỗi khách hàng: Khách hàng HÀ có giá trị đơn hàng trung bình cao nhất (1,600), theo sau là CƯỜNG (1,500). Khách hàng BÌNH có giá trị trung bình thấp nhất (50).